- helm/linkerd2-app/Chart.yaml
This updates the app icon to use our static web assets server.
> Update app icon

- CHANGELOG.md
- helm/linkerd2-app/Chart.yaml
- helm/linkerd2-app/templates/config.yaml
- helm/linkerd2-app/templates/destination-rbac.yaml
- helm/linkerd2-app/templates/proxy-injector.yaml
- helm/linkerd2-app/templates/psp.yaml
- helm/linkerd2-app/templates/sp-validator.yaml
- helm/linkerd2-app/templates/web.yaml
- helm/linkerd2-app/values.yaml
syncing in upstream changes between 2.9.0 and 2.9.1
> update to 2.9.1

- CHANGELOG.md
- helm/linkerd2-app/Chart.yaml
Towards https://github.com/giantswarm/giantswarm/issues/19663
> Update linkerd2-app chart metadata

- README.md
> Update docs to point latest version of linkerd

- CHANGELOG.md
- tests/ats/Pipfile
- tests/ats/Pipfile.lock
This PR updates pytest-helm-charts from beta to 0.7.0
> Update pytest-helm-charts from beta to 0.7.0

- CHANGELOG.md
- README.md
- helm/linkerd2-app/templates/_post-hook-init-hack.tpl
- helm/linkerd2-app/templates/destination.yaml
- helm/linkerd2-app/templates/proxy-injector.yaml
- helm/linkerd2-app/values.schema.json
- helm/linkerd2-app/values.yaml
Towards https://github.com/giantswarm/roadmap/issues/1174
> Post hook hack as workaround 

- helm/linkerd2-app/templates/destination.yaml
- helm/linkerd2-app/templates/proxy-injector.yaml
> deployment/destination: Fix postHookInitHack check.

- README.md
This PR replaces a relative link in README.md with an absolute one so it works on happa
> relative link replaced with absolute

- README.md
namespace and cluster have been deprecated in favor of target-namespace
and cluster-name
This PR...
> Fix App template command paramenters.

- CHANGELOG.md
- helm/linkerd2-app/README.md
- helm/linkerd2-app/templates/_post-hook-init-hack.tpl
- helm/linkerd2-app/templates/destination.yaml
- helm/linkerd2-app/templates/identity.yaml
- helm/linkerd2-app/templates/proxy-injector.yaml
- helm/linkerd2-app/values.schema.json
- helm/linkerd2-app/values.yaml
- helm/partials/templates/_debug.tpl
- helm/partials/templates/_proxy-init.tpl
- helm/partials/templates/_proxy.tpl
This PR adds a registry switch to `values.yaml` to ensure clusters choose the right registry (e.g. aliyun for China)
> add registry switch

- .circleci/config.yml
- .github/pull_request_template.md
- README.md
- tests/ats/README.md
This PR renames ~app to `linkerd-control-plane`, matching upstream.~ main branch to `main`.
> rename branch to main

- Makefile.local.mk
- vendir.lock.yml
- vendir.yml
This PR reduces the hardcoded values in the Makefile.
For that, I moved some actions directly to vendir. Added also a looping
mechanism over dependencies to automatically update the Chart.yaml
> Reduce hardcoded deps in Makefile.

- CHANGELOG.md
- helm/linkerd-control-plane/values.yaml
This PR adds suggested changes by @danibaeyens in https://github.com/giantswarm/linkerd-control-plane-app/pull/130
> Skip proxy injection in giantswarm namespace

- README.md
> Update readme steps and linkerd-viz installation process

- CHANGELOG.md
- helm/linkerd-control-plane/Chart.yaml
Towards https://github.com/giantswarm/roadmap/issues/2381
> Replace icon and add logo

- CHANGELOG.md
- helm/linkerd-control-plane/Chart.yaml
- helm/linkerd-control-plane/README.md
- helm/linkerd-control-plane/charts/partials/templates/_proxy.tpl
- helm/linkerd-control-plane/templates/destination.yaml
- helm/linkerd-control-plane/templates/identity.yaml
- helm/linkerd-control-plane/templates/proxy-injector.yaml
- helm/linkerd-control-plane/values.schema.json
- helm/linkerd-control-plane/values.yaml
- vendir.lock.yml
- vendor sync
- update changelog and Chart.yaml
- Update readme
- update schema
This PR...
> Update chart from upstream

- CHANGELOG.md
- tests/ats/test_linkerd.py
> Update CNI app version in tests

- README.md
> Add note about schedulingFailure to Troubleshooting section of README

- CHANGELOG.md
- helm/linkerd-control-plane/Chart.yaml
- helm/linkerd-control-plane/values.yaml
- tests/ats/test_linkerd.py
- vendir.lock.yml
> upgrade app to linkerd 2.13.6

- .abs/main.yaml
- .circleci/config.yml
- CHANGELOG.md
- tests/ats/Pipfile
- tests/ats/Pipfile.lock
- tests/ats/test_linkerd.py
> Update ATS to 0.4.1

- .circleci/config.yml
- CHANGELOG.md
- tests/ats/test_linkerd.py
- Update Linkerd CNI for CI
- update changelog
This PR...
> Update Linkerd CNI app in tests

- CHANGELOG.md
- helm/linkerd-control-plane/values.yaml
- tests/ats/test_linkerd.py
Towards https://github.com/giantswarm/roadmap/issues/3040
> Adopt gsoci.azurecr.io oci registry

- CHANGELOG.md
- helm/linkerd-control-plane/templates/vpa.yaml
- helm/linkerd-control-plane/values.schema.json
- helm/linkerd-control-plane/values.yaml
- vendir.lock.yml
This PR adds VPA.
Towards https://github.com/giantswarm/roadmap/issues/3114
> add VPA CRs to control-plane deployments
